# Generated by rust2rpm 16
%bcond_without check
%global __cargo_skip_build 0

%global crate drg

Name:           rust-%{crate}
Version:        0.5.1
Release:        1.20210406114535497168.main.19.ga7278ba%{?dist}
Summary:        Command line tool to interact with a drogue-cloud instance

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/drg
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Command line tool to interact with a drogue-cloud instance.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/drg

%prep
%autosetup -p1 -n %{crate}-%{version}
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 17 18:16:00 CEST 2021 Jean-Baptiste Trystram <jbtrystram@redhat.com> - 0.5.0-1
- Initial package
