# Generated by rust2rpm 16
%bcond_without check
%global __cargo_skip_build 0

%global crate drg

Name:           rust-%{crate}
Version:        0.3.0
Release:        1.20210406124250172846.main.21.g42fcff4%{?dist}
Summary:        Command line tool to interact with a drogue-cloud instance

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/drg
Source:         drg-0.3.0.tar.gz

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Command line tool to interact with a drogue-cloud instance.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%{_bindir}/drg

%prep
%autosetup -p1 -n %{crate}-%{version}
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Apr 06 13:44:55 CEST 2021 Jens Reimann <jreimann@redhat.com> - 0.3.0-1
- Initial package
