# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rust-drg.spec

# add or remove files that should be synced
synced_files:
  - rust-drg.spec
  - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: drg
# downstream (Fedora) RPM package name
downstream_package_name: rust-drg

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: master
