name: Tests

# all the branches is fine. This shouldn't run on external PRs though
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    # if: github.event.pull_request.head.repo.full_name == 'drogue-iot/drg'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cleanup apps
        shell: bash
        run: .github/scripts/tests/clean_apps.sh
        env:
          DROGUE_SANDBOX_URL: ${{secrets.DROGUE_SANDBOX_URL}}
          DROGUE_SANDBOX_ACCESS_KEY: ${{secrets.DROGUE_SANDBOX_ACCESS_KEY}}
          DROGUE_SANDBOX_USERNAME: ${{secrets.DROGUE_SANDBOX_USERNAME}}

      - name: Tests
        run: cargo test
        env:
          DROGUE_SANDBOX_URL: ${{secrets.DROGUE_SANDBOX_URL}}
          DROGUE_SANDBOX_ACCESS_KEY: ${{secrets.DROGUE_SANDBOX_ACCESS_KEY}}
          DROGUE_SANDBOX_KEY_PREFIX: ${{secrets.DROGUE_SANDBOX_KEY_PREFIX}}
          DROGUE_SANDBOX_USERNAME: ${{secrets.DROGUE_SANDBOX_USERNAME}}
